# Generated by Django 3.2.21 on 2023-10-03 13:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("platform_plugin_forum_email_notifier", "0002_forumnotificationdigest"),
    ]

    operations = [
        migrations.AddField(
            model_name="forumnotificationdigest",
            name="last_sent",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
